# Python Tutorial 

## Lists 

In [7]:
fruits = ['orange', 'pear', 'banana', 'kiwi', 'apple']


In [8]:
fruits.append('mango')

In [9]:
fruits

['orange', 'pear', 'banana', 'kiwi', 'apple', 'mango']

In [10]:
fruits.remove('mango')

In [11]:
fruits

['orange', 'pear', 'banana', 'kiwi', 'apple']

In [14]:
fruits.sort()
fruits

['apple', 'banana', 'kiwi', 'orange', 'pear']

## Sets 

In [16]:
test_set = set(fruits)
test_set


{'apple', 'banana', 'kiwi', 'orange', 'pear'}

In [17]:
test_set.add('mango')
test_set.remove('apple')
test_set

{'banana', 'kiwi', 'mango', 'orange', 'pear'}

In [18]:
vegetables=['carrot','Pea','Onion','Potato']

In [86]:
grocery = set(fruits).union(set(vegetables))
grocery

{'Onion',
 'Pea',
 'Potato',
 'apple',
 'banana',
 'carrot',
 'kiwi',
 'orange',
 'pear'}

In [26]:
type(grocery)

set

In [29]:
grocery.difference(set(fruits))

{'Onion', 'Pea', 'Potato', 'carrot'}

## Array

In [30]:
import numpy as np

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.array([2,3,1,0])

array([2, 3, 1, 0])

In [46]:
# returns evenly spaced numbers over a specified interval
np.linspace(1,4,7)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [50]:
np.arange(2,5,0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8])

In [51]:
np.arange(4)

array([0, 1, 2, 3])

In [52]:
a = np.array([10,20,30,40])
b = np.arange(4)

In [57]:
a+b

array([10, 21, 32, 43])

In [58]:
a-b

array([10, 19, 28, 37])

In [59]:
# creating an array by specifying rows and columns
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Dictionary

In [60]:
dic_test = {'key1':1,'key2':2}

In [61]:
dic_test.keys()

dict_keys(['key1', 'key2'])

In [63]:
dic_test.values()

dict_values([1, 2])

In [65]:
dic_test['key1']

1

## Loop 

In [68]:
for num in range(5):
    print(num)

0
1
2
3
4


In [71]:
for i in range (0,len(range(5))):
    print(i+1)

1
2
3
4
5


In [75]:
x=0
while x<5:
    print('The new value is {}'.format(x))
    x+=1

The new value is 0
The new value is 1
The new value is 2
The new value is 3
The new value is 4


In [76]:
for x in range(1,3):
    for y in range(1,3):
        print('{}*{} = {}'.format(x,y,x*y))

1*1 = 1
1*2 = 2
2*1 = 2
2*2 = 4


In [81]:
for i in range(3):
    print(i)
    i+=1
    if i==1:
        break

0


## Split 

In [82]:
test_split = 'This is a test * to split this string.'

In [83]:
test_split.split('*')

['This is a test ', ' to split this string.']

In [85]:
test_split.split(' ')

['This', 'is', 'a', 'test', '*', 'to', 'split', 'this', 'string.']

## Regular Expressions 

In [87]:
import re

In [105]:
# \D searches for numbers
re.sub(r'\D','',"45454 232 # Hello")

'45454232'

In [93]:
# Remove everything except alphabet and spaces
re.sub(r'[^a-zA-Z\s]','','45454 232 # Hello')

'   Hello'

In [110]:
# Remove everything except numbers and spaces
re.sub(r'[^\d\s]','','45454 232 # Hello')
# same as above re.sub(r'[^0-9\s]','')

'45454 232  '

In [103]:
re.sub(r'\w+\d\s*\d\s*\d\w+','END', ' This is the pattern we find to find .. xx1 2   3xx .. end of expression')

' This is the pattern we find to find .. END .. end of expression'

## Functions 

In [129]:
def changeme(x):
    x.append([5,6,7,8])
    print(x)
    return

In [130]:
changeme([1,2,3,4])

[1, 2, 3, 4, [5, 6, 7, 8]]


In [139]:
def area (length,breadth):
    area = length*breadth
    print("The area of a rectangle with length '{}' and breadth '{}' is {}.".format(length, breadth, area))

In [140]:
area(2,3)

The area of a rectangle with length '2' and breadth '3' is 6.
