In [1]:
import numpy as np
import pandas as pd

In [2]:
A = np.arange(6).reshape(2,3) + 0.3
print(A)

[[0.3 1.3 2.3]
 [3.3 4.3 5.3]]


In [3]:
B = np.arange(8).reshape(2,4) + 0.5
print(B)

[[0.5 1.5 2.5 3.5]
 [4.5 5.5 6.5 7.5]]


In [4]:
C = np.arange(12).reshape(3,4) + 0.3
print(C)

[[ 0.3  1.3  2.3  3.3]
 [ 4.3  5.3  6.3  7.3]
 [ 8.3  9.3 10.3 11.3]]


### Stacking arrays horizontally 

In [5]:
np.hstack([B,A])

array([[0.5, 1.5, 2.5, 3.5, 0.3, 1.3, 2.3],
       [4.5, 5.5, 6.5, 7.5, 3.3, 4.3, 5.3]])

In [6]:
np.concatenate([B,A],axis = 1)

array([[0.5, 1.5, 2.5, 3.5, 0.3, 1.3, 2.3],
       [4.5, 5.5, 6.5, 7.5, 3.3, 4.3, 5.3]])

### Stacking arrays vertically 

In [7]:
np.vstack([B,C])

array([[ 0.5,  1.5,  2.5,  3.5],
       [ 4.5,  5.5,  6.5,  7.5],
       [ 0.3,  1.3,  2.3,  3.3],
       [ 4.3,  5.3,  6.3,  7.3],
       [ 8.3,  9.3, 10.3, 11.3]])

In [8]:
np.concatenate([B,C],axis = 0)

array([[ 0.5,  1.5,  2.5,  3.5],
       [ 4.5,  5.5,  6.5,  7.5],
       [ 0.3,  1.3,  2.3,  3.3],
       [ 4.3,  5.3,  6.3,  7.3],
       [ 8.3,  9.3, 10.3, 11.3]])

## Joins 

In [9]:
gold = pd.read_csv('gold_top5.csv',index_col=0)
silver = pd.read_csv('silver_top5.csv',index_col=0)
bronze = pd.read_csv('bronze_top5.csv',index_col=0)
medal_list = [gold,silver,bronze]

In [10]:
pd.concat(medal_list,keys = ['bronze','silver','gold'],axis=1,join='inner')

bronze  silver    gold
                 Total   Total   Total
Country                               
United States   2088.0  1195.0  1052.0
Soviet Union     838.0   627.0   584.0
United Kingdom   498.0   591.0   505.0

In [11]:
pd.concat(medal_list,keys = ['bronze','silver','gold'],axis=1,join='outer')

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


bronze  silver    gold
                 Total   Total   Total
France             NaN   461.0   475.0
Germany          407.0     NaN   454.0
Italy            460.0   394.0     NaN
Soviet Union     838.0   627.0   584.0
United Kingdom   498.0   591.0   505.0
United States   2088.0  1195.0  1052.0