In [1]:
import numpy as np
import pandas as pd

In [3]:
A = np.arange(6).reshape(2,3) + 0.3
print(A)

[[0.3 1.3 2.3]
 [3.3 4.3 5.3]]


In [4]:
B = np.arange(8).reshape(2,4) + 0.5
print(B)

[[0.5 1.5 2.5 3.5]
 [4.5 5.5 6.5 7.5]]


In [5]:
C = np.arange(12).reshape(3,4) + 0.3
print(C)

[[ 0.3  1.3  2.3  3.3]
 [ 4.3  5.3  6.3  7.3]
 [ 8.3  9.3 10.3 11.3]]


### Stacking arrays horizontally 

In [6]:
np.hstack([B,A])

array([[0.5, 1.5, 2.5, 3.5, 0.3, 1.3, 2.3],
       [4.5, 5.5, 6.5, 7.5, 3.3, 4.3, 5.3]])

In [7]:
np.concatenate([B,A],axis = 1)

array([[0.5, 1.5, 2.5, 3.5, 0.3, 1.3, 2.3],
       [4.5, 5.5, 6.5, 7.5, 3.3, 4.3, 5.3]])

### Stacking arrays vertically 

In [9]:
np.vstack([B,C])

array([[ 0.5,  1.5,  2.5,  3.5],
       [ 4.5,  5.5,  6.5,  7.5],
       [ 0.3,  1.3,  2.3,  3.3],
       [ 4.3,  5.3,  6.3,  7.3],
       [ 8.3,  9.3, 10.3, 11.3]])

In [10]:
np.concatenate([B,C],axis = 0)

array([[ 0.5,  1.5,  2.5,  3.5],
       [ 4.5,  5.5,  6.5,  7.5],
       [ 0.3,  1.3,  2.3,  3.3],
       [ 4.3,  5.3,  6.3,  7.3],
       [ 8.3,  9.3, 10.3, 11.3]])

## Joins 

In [25]:
gold = pd.read_csv('Gold.csv',index_col=0)
silver = pd.read_csv('Silver.csv',index_col=0)
bronze = pd.read_csv('Bronze.csv',index_col=0)
medal_list = [gold,silver,bronze]

In [26]:
pd.concat(medal_list,keys = ['bronze','silver','gold'],axis=1,join='inner')

bronze                        silver          \
                  Country   Total               Country   Total   
NOC                                                               
USA         United States  2088.0         United States  1195.0   
URS          Soviet Union   838.0          Soviet Union   627.0   
GBR        United Kingdom   498.0        United Kingdom   591.0   
FRA                France   378.0                France   461.0   
GER               Germany   407.0               Germany   350.0   
..                    ...     ...                   ...     ...   
SEN               Senegal     NaN               Senegal     1.0   
SUD                 Sudan     NaN                 Sudan     1.0   
TGA                 Tonga     NaN                 Tonga     1.0   
BDI               Burundi     1.0               Burundi     NaN   
UAE  United Arab Emirates     1.0  United Arab Emirates     NaN   

                     gold          
                  Country   Total  
NOC                                
USA         United States  1052.0  
URS          Soviet Union   584.0  
GBR        United Kingdom   505.0  
FRA                France   475.0  
GER               Germany   454.0  
..                    ...     ...  
SEN               Senegal     NaN  
SUD                 Sudan     NaN  
TGA                 Tonga     NaN  
BDI               Burundi     NaN  
UAE  United Arab Emirates     NaN  

[138 rows x 6 columns]

In [27]:
pd.concat(medal_list,keys = ['bronze','silver','gold'],axis=1,join='outer')

bronze                        silver          \
                  Country   Total               Country   Total   
NOC                                                               
USA         United States  2088.0         United States  1195.0   
URS          Soviet Union   838.0          Soviet Union   627.0   
GBR        United Kingdom   498.0        United Kingdom   591.0   
FRA                France   378.0                France   461.0   
GER               Germany   407.0               Germany   350.0   
..                    ...     ...                   ...     ...   
SEN               Senegal     NaN               Senegal     1.0   
SUD                 Sudan     NaN                 Sudan     1.0   
TGA                 Tonga     NaN                 Tonga     1.0   
BDI               Burundi     1.0               Burundi     NaN   
UAE  United Arab Emirates     1.0  United Arab Emirates     NaN   

                     gold          
                  Country   Total  
NOC                                
USA         United States  1052.0  
URS          Soviet Union   584.0  
GBR        United Kingdom   505.0  
FRA                France   475.0  
GER               Germany   454.0  
..                    ...     ...  
SEN               Senegal     NaN  
SUD                 Sudan     NaN  
TGA                 Tonga     NaN  
BDI               Burundi     NaN  
UAE  United Arab Emirates     NaN  

[138 rows x 6 columns]